services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "4443:443"
      - "8081:80"
    depends_on:
      - frontend
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
